### ISSUE TITLE
Module not found 

### ISSUE THREAD

**Issue by One3One** [thaddeusdiamond/cardano-nft-mint-frontend#1]
**I'm not really well versed with webpack, so this might be a weird question. I have this error when I run npm run build. Can I know what I did wrong here. I really would like to learn more. Thank you**

ERROR in ./js/nft-toolkit/nft-policy.js 1:0-57
Module not found: Error: Can't resolve 'lucid-cardano' in 'C:\Users\One\Downloads\cardano-nft-mint-frontend-master\src\js\nft-toolkit'
 @ ./js/pages/nft-creator.js 8:0-58 46:19-55 67:48-90 157:4-46 165:43-84 166:29-67 168:32-51 226:51-73 279:36-72 279:151-187
 @ ./js/library.js 8:0-53 8:0-53

ERROR in ./js/pages/nft-creator.js 1:0-57
Module not found: Error: Can't resolve 'lucid-cardano' in 'C:\Users\One\Downloads\cardano-nft-mint-frontend-master\src\js\pages'
 @ ./js/library.js 8:0-53 8:0-53

ERROR in ./js/pages/nft-creator.js 4:0-41
Module not found: Error: Can't resolve './/secrets.js' in 'C:\Users\One\Downloads\cardano-nft-mint-frontend-master\src\js\pages'
 @ ./js/library.js 8:0-53 8:0-53

ERROR in ./js/pages/vending-machine.js 2:0-36
Module not found: Error: Can't resolve 'lucid-cardano' in 'C:\Users\One\Downloads\cardano-nft-mint-frontend-master\src\js\pages'
 @ ./js/library.js 10:0-61 10:0-61

ERROR in ./js/pages/vending-machine.js 4:0-41
Module not found: Error: Can't resolve './/secrets.js' in 'C:\Users\One\Downloads\cardano-nft-mint-frontend-master\src\js\pages'
 @ ./js/library.js 10:0-61 10:0-61

ERROR in ./js/third-party/lucid-inst.js 1:0-48
Module not found: Error: Can't resolve 'lucid-cardano' in 'C:\Users\One\Downloads\cardano-nft-mint-frontend-master\src\js\third-party'
 @ ./js/library.js 4:0-57 4:0-57

6 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.73.0 compiled with 6 errors and 2 warnings in 3833 ms

**Comment by thaddeusdiamond** [comment]
Hiya! Take a look at the readme.  You need to create a `secrets.js` file in `src/js/` with the following contents:

```js
export const PAYMENT_ADDR = "<PAYMENT_ADDR>"
export const BLOCKFROST_PROJ = "<BLOCKFROST_PROJ>"
export const MINT_PRICE = <MINT_PRICE_IN_LOVELACE>;
export const LOWER_LIMIT = <MIN_TO_MINT_USUALLY_ONE>;
export const UPPER_LIMIT = <MAX_TO_MINT_AT_ONCE>;
```

As for the other error, please run `npm i` before running the program.  That will install the dependency on `lucid-cardano`.  Let me know if that resolves your issue.  I will update the README.

**Comment by One3One** [comment]
Hi @thaddeusdiamond ! yes I did create the secrets.js file in the directory that you mentioned and run npm install as well. Fixed the lucid-cardano error. I think the problem right now is the pathing of secrets.js or I'm not sure..

ERROR in ./js/pages/nft-creator.js 171:43-63
export 'MAX_QUANTITY' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 8:0-53 8:0-53

ERROR in ./js/pages/nft-creator.js 204:45-72
export 'REQUIRED_POLICY_KEY' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 8:0-53 8:0-53

ERROR in ./js/pages/nft-creator.js 210:42-69
export 'REQUIRED_POLICY_MIN' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 8:0-53 8:0-53

ERROR in ./js/pages/nft-creator.js 211:138-165
export 'REQUIRED_POLICY_MIN' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 8:0-53 8:0-53

ERROR in ./js/pages/nft-creator.js 211:189-216
export 'REQUIRED_POLICY_KEY' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 8:0-53 8:0-53

ERROR in ./js/pages/vending-machine.js 33:33-60
export 'REQUIRED_POLICY_KEY' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 10:0-61 10:0-61

ERROR in ./js/pages/vending-machine.js 39:46-84
export 'REQUIRED_VENDING_MACHINE_RATIO' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 10:0-61 10:0-61

ERROR in ./js/pages/vending-machine.js 40:147-174
export 'REQUIRED_POLICY_KEY' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 10:0-61 10:0-61

ERROR in ./js/pages/vending-machine.js 40:188-226
export 'REQUIRED_VENDING_MACHINE_RATIO' (imported as 'Secrets') was not found in '../secrets.js' (possible exports: BLOCKFROST_PROJ, LOWER_LIMIT, MINT_PRICE, PAYMENT_ADDR, UPPER_LIMIT)
 @ ./js/library.js 10:0-61 10:0-61

![Capture](https://user-images.githubusercontent.com/107629808/180577796-091b673d-9267-488d-a854-c3eaf11616fa.PNG)

I think I put it in the correct directory.. Is there any way to fix it ><

**Comment by thaddeusdiamond** [comment]
Couple more things need to go in that file.  I updated the README:
```
// Blockfrost.io keys (used across pages)
export const BLOCKFROST_PROJ = "<BLOCKFROST_PROJ>"
// Used in drop-payment.js
export const PAYMENT_ADDR = "<PAYMENT_ADDR>"
export const MINT_PRICE = <MINT_PRICE_IN_LOVELACE>;
export const LOWER_LIMIT = <MIN_TO_MINT_USUALLY_ONE>;
export const UPPER_LIMIT = <MAX_TO_MINT_AT_ONCE>;
// Used in nft-creator.js
export const MAX_QUANTITY = <MAX_QUANTITY_OF_FTS_FOR_1OF1_MINTER>;
export const REQUIRED_POLICY_KEY = "<GATEKEEPING_NFT_POLICY>";
// Used in vending-machine.js
export const REQUIRED_POLICY_MIN = <MIN_TO_USE_1OF1_MINTER>;
export const REQUIRED_VENDING_MACHINE_RATIO = <RATIO_FOR_AMOUNT_TO_VEND_PER_GATEKEEPING_NFT>;
```

**Comment by One3One** [comment]
Awesome ! @thaddeusdiamond , that fixed most of the issue :D but right now I only have this one error...

```
WARNING in ../node_modules/lucid-cardano/custom_modules/cardano-multiplatform-lib-browser/cardano_multiplatform_lib_bg.js 16746:14-53
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/lucid-cardano/custom_modules/cardano-multiplatform-lib-browser/cardano_multiplatform_lib.js 2:0-50 2:0-50
 @ ../node_modules/lucid-cardano/dist/index.js 871:59-149
 @ ./js/third-party/lucid-inst.js 1:0-48 33:11-20 33:25-35
 @ ./js/library.js 4:0-57 4:0-57

1 warning has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.73.0 compiled with 1 warning in 954 ms
```
Any idea on how to fix this one hm 😭

**Comment by thaddeusdiamond** [comment]
Just a warning, you should be good to go! If you can run:

```
npm i static-server
cd dist/
static-server
```

And then see the webpages at `http://localhost:9080/nft-creator.html` then you're in business.

**Comment by thaddeusdiamond** [comment]
@One3One sorry for the delay in following up here to see if there's anything else.  If not, feel free to close this issue.

**Comment by One3One** [comment]
Hi there @thaddeusdiamond , sorry for the delay as well. I got this problem actually.
It says forbidden.

![image](https://user-images.githubusercontent.com/107629808/193834126-7cc69633-e2ef-408a-8798-8864c6fc2d6b.png)

this is the output at the terminal 

![image](https://user-images.githubusercontent.com/107629808/193834293-a54d5e8b-cab8-4712-8c96-d1c84baf6c84.png)'

I'm not sure why , probably a problem at my end

**Comment by thaddeusdiamond** [comment]
Yeah there is no root module in this package.  You would have to go to `localhost:9080/nft-creator.html` or another page directly.

**Comment by One3One** [comment]
Perfect! Sorry for taking your time, I'm not really familiar with static-server but It's now working! Thank you @thaddeusdiamond ! 
Time to play around :D .
I will now close this issue.
Love Wild Tangz! <3

![image](https://user-images.githubusercontent.com/107629808/193897331-07e1a97d-48ea-4945-bc44-21ac170f03af.png)

**Comment by thaddeusdiamond** [comment]
Glad to hear, thank you!
